# Generated by Django 4.2.6 on 2023-10-07 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.utils
import images.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=255, upload_to=images.utils.path_to_uploaded_img)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('expiration_time', models.IntegerField(validators=[images.validators.validate_expiration_time])),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiring_link', to='images.image')),
            ],
        ),
    ]
